"""Add day_id foreign key to Fuel table and populate foreign key column.

Revision ID: a44260a8b664
Revises: 495b2bbf3ff7
Create Date: 2025-06-04 06:37:26.893222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44260a8b664'
down_revision = '495b2bbf3ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fuel_day_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'day', ['day_id'], ['id'])

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payslip_day_id'), ['day_id'], unique=False)
        batch_op.create_foreign_key(None, 'day', ['day_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payslip_day_id'))
        batch_op.drop_column('day_id')

    with op.batch_alter_table('fuel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_fuel_day_id', 'day', ['day_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
