"""Give ExpenseOccurance>frequency>db.Enum a 'name'

Revision ID: 41540f83cc27
Revises: e9ef0415da38
Create Date: 2024-10-22 18:15:33.876347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41540f83cc27'
down_revision = 'e9ef0415da38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_occurance', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=postgresql.ENUM('WEEKLY', 'MONTHLY', 'YEARLY', 'ONE_OFF', name='timefrequency'),
               type_=sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', 'ONE_OFF', name='time_frequency'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_occurance', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', 'ONE_OFF', name='time_frequency'),
               type_=postgresql.ENUM('WEEKLY', 'MONTHLY', 'YEARLY', 'ONE_OFF', name='timefrequency'),
               existing_nullable=False)

    # ### end Alembic commands ###
