"""change Day model so that truck_id column nullable is True.

Revision ID: 4527f935ee68
Revises: 175e3ec6a390
Create Date: 2024-11-01 18:06:27.476922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4527f935ee68'
down_revision = '175e3ec6a390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.alter_column('truck_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.alter_column('truck_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
