"""Add fuel field to Day model and update overnight, fuel validation and split validation of Job modlel

Revision ID: 4b7d8fa3c971
Revises: 5348ee9b8123
Create Date: 2024-09-09 05:57:02.175478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7d8fa3c971'
down_revision = '5348ee9b8123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('fuel')

    # ### end Alembic commands ###
