"""remove test from Day model

Revision ID: 89f18f48cf69
Revises: 61e7a7a53ea8
Create Date: 2024-09-10 06:25:00.813678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f18f48cf69'
down_revision = '61e7a7a53ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
