"""Change relationship between Day and Job. Add ondelete=restrict to job fk

Revision ID: 9935b90ffe5f
Revises: a8c166ef389c
Create Date: 2025-02-28 18:33:05.173661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9935b90ffe5f'
down_revision = 'a8c166ef389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('job_day_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'day', ['day_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_day_id_fkey', 'day', ['day_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
