"""Add IncorrectMileage model

Revision ID: d7b1890394f2
Revises: 9935b90ffe5f
Create Date: 2025-03-03 20:12:14.729993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b1890394f2'
down_revision = '9935b90ffe5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incorrect_mileage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('previous_end_mileage', sa.Float(), nullable=False),
    sa.Column('next_start_mileage', sa.Float(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('previous_day_id', sa.Integer(), nullable=True),
    sa.Column('next_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['anomaly.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['previous_day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incorrect_mileage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incorrect_mileage_next_date'), ['next_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incorrect_mileage_previous_date'), ['previous_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incorrect_mileage_truck_id'), ['truck_id'], unique=False)

    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('week_number')

    with op.batch_alter_table('incorrect_mileage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incorrect_mileage_truck_id'))
        batch_op.drop_index(batch_op.f('ix_incorrect_mileage_previous_date'))
        batch_op.drop_index(batch_op.f('ix_incorrect_mileage_next_date'))

    op.drop_table('incorrect_mileage')
    # ### end Alembic commands ###
