"""Add fuel to day model

Revision ID: ee459fa80588
Revises: 4b7d8fa3c971
Create Date: 2024-09-09 14:22:57.033454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee459fa80588'
down_revision = '4b7d8fa3c971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
