"""Add day_id fk to Fuel and Payslip tables.

Revision ID: f3de9805f6ad
Revises: d7b1890394f2
Create Date: 2025-06-04 06:48:13.130839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'f3de9805f6ad'
down_revision = 'd7b1890394f2'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    
    with op.batch_alter_table('fuel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.Integer(), nullable=True))

    fuel_result = connection.execute(
        text("""
        UPDATE fuel 
        SET day_id = day.id 
        FROM day 
        WHERE fuel.date = day.date 
        AND fuel.truck_id = day.truck_id
        AND fuel.day_id IS NULL
        """)
    )
    payslip_result = connection.execute(
        text("""
        UPDATE payslip
        SET day_id = day.id
        FROM day
        WHERE payslip.date = day.date
        AND payslip.driver_id = day.driver_id
        AND payslip.day_id IS NULL
        """)
    )

    with op.batch_alter_table('fuel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_day_id'), ['day_id'], unique=False)
        batch_op.create_foreign_key('fk_fuel_day_id', 'day', ['day_id'], ['id'])

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslip_day_id'), ['day_id'], unique=False)
        batch_op.create_foreign_key('fk_fuel_day_id', 'day', ['day_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payslip_day_id'))
        batch_op.drop_column('day_id')

    with op.batch_alter_table('fuel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fuel_day_id'))
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###
