"""empty message

Revision ID: 1983fd49975c
Revises: 615139181c4d
Create Date: 2024-12-22 15:41:37.585435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1983fd49975c'
down_revision = '615139181c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_response', schema=None) as batch_op:
        batch_op.drop_column('all_suggestions_helpful')
        batch_op.drop_column('historical_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historical_context', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('all_suggestions_helpful', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
