"""empty message

Revision ID: c4cfc77d89fa
Revises: 615139181c4d
Create Date: 2024-12-31 12:59:18.503268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cfc77d89fa'
down_revision = '615139181c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint('day_anomaly_suggestion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_processed_response', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fuel_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint('fuel_anomaly_suggestion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_processed_response', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('job_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint('job_anomaly_suggestion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_processed_response', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('missing_entry_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint('missing_entry_suggestion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_processed_response', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_constraint('_driver_date_ps_uc', type_='unique')
        batch_op.create_unique_constraint('_driver_week_payslip_uc', ['driver_id', 'week_number'])

    with op.batch_alter_table('payslip_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint('payslip_anomaly_suggestion_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_processed_response', ['id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payslip_anomaly_suggestion_id_fkey', 'ai_processed_response', ['id'], ['id'])

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_constraint('_driver_week_payslip_uc', type_='unique')
        batch_op.create_unique_constraint('_driver_date_ps_uc', ['driver_id', 'date'])

    with op.batch_alter_table('missing_entry_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('missing_entry_suggestion_id_fkey', 'ai_processed_response', ['id'], ['id'])

    with op.batch_alter_table('job_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_anomaly_suggestion_id_fkey', 'ai_processed_response', ['id'], ['id'])

    with op.batch_alter_table('fuel_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fuel_anomaly_suggestion_id_fkey', 'ai_processed_response', ['id'], ['id'])

    with op.batch_alter_table('day_anomaly_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('day_anomaly_suggestion_id_fkey', 'ai_processed_response', ['id'], ['id'])

    # ### end Alembic commands ###
