"""empty message

Revision ID: c6d600761f5f
Revises: 4527f935ee68
Create Date: 2024-11-17 19:16:48.095110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d600761f5f'
down_revision = '4527f935ee68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('verification_data', sa.JSON(), nullable=True),
    sa.Column('timeframe', sa.Enum('DAILY', 'WEEKLY', name='timeframeenum'), nullable=True),
    sa.Column('error_type', sa.Enum('INFO', 'MISSING_DATA', 'INCORRECT_DATA', 'SUSPICIOUS_ACTIVITY', name='errortypeenum'), nullable=True),
    sa.Column('primary_fault_area', sa.Enum('DAY_FUEL', 'DAY_MILEAGE', 'DAY_EARNED', 'FUEL', 'PAYSLIP', 'JOB', name='faultareaenum'), nullable=True),
    sa.Column('secondary_fault_area', sa.Enum('DAY_FUEL', 'DAY_MILEAGE', 'DAY_EARNED', 'FUEL', 'PAYSLIP', 'JOB', name='faultareaenum'), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
